import os
import re
import time
from typing import Dict, Any, List
from pathlib import Path
from src.ai.tools.base_tool import BaseTool, ToolResult, ToolParameter, success_result, error_result
from src.utils.logger import get_logger

log = get_logger("CheckLayoutTool")

class CheckLayoutTool(BaseTool):
    """
    Check the layout hierarchy and CSS properties for a specific HTML element.
    This helps the AI debug if an element is hidden due to `overflow`, `height` clipping, or `display: none`.
    """
    name = "check_layout"
    description = "Inspect why a UI element is missing or cut off. Extracts the DOM hierarchy up to the <body> tag and prints all CSS rules applied to its parent containers to debug layout overflow and heights."
    
    parameters = [
        ToolParameter("path", "string", "Path to the HTML file (or use 'file')", required=False),
        ToolParameter("selector", "string", "CSS selector for the missing element (e.g., '#startBtn' or '.control-btn')", required=True)
    ]
    
    def validate_params(self, params: Dict[str, Any]) -> tuple[bool, str]:
        if "file" in params and "path" not in params:
            params["path"] = params["file"]
            
        if "path" not in params:
            return False, "Missing required parameter: path"
        if "selector" not in params:
            return False, "Missing required parameter: selector"
            
        return super().validate_params(params)
    
    def execute(self, params: Dict[str, Any]) -> ToolResult:
        start_time = time.time()
        file_path = params.get("path")
        selector = params.get("selector")
        
        try:
            from bs4 import BeautifulSoup
        except ImportError:
            return error_result("BeautifulSoup4 is not installed. Run `pip install beautifulsoup4` to use this tool.")
            
        try:
            resolved_path = self._resolve_path(file_path)
            if not resolved_path.exists():
                return error_result(f"File not found: {file_path}")
                
            content = resolved_path.read_text(encoding='utf-8', errors='ignore')
            soup = BeautifulSoup(content, "html.parser")
            
            # Find the element
            try:
                elements = soup.select(selector)
            except Exception as e:
                return error_result(f"Invalid CSS selector '{selector}': {e}")
                
            if not elements:
                return error_result(f"Element with selector '{selector}' not found in the HTML structure. It might be dynamically generated by JS, or deleted.")
                
            target = elements[0]
            
            # Walk up the parent hierarchy
            hierarchy = []
            current = target
            classes_to_check = set()
            ids_to_check = set()
            tags_to_check = set()
            
            while current and current.name != '[document]':
                # Build representation
                node_repr = current.name
                if current.get('id'):
                    node_repr += f"#{current.get('id')}"
                    ids_to_check.add(current.get('id'))
                if current.get('class'):
                    if isinstance(current.get('class'), list):
                        node_repr += "." + ".".join(current.get('class'))
                        classes_to_check.update(current.get('class'))
                    else:
                        node_repr += "." + current.get('class')
                        classes_to_check.add(current.get('class'))
                        
                tags_to_check.add(current.name)
                
                inline_style = current.get('style', '')
                if inline_style:
                    node_repr += f" (inline style: {inline_style})"
                    
                hierarchy.append(node_repr)
                
                if current.name.lower() == 'body':
                    break
                    
                current = current.parent
                
            # Now extract all CSS blocks that match any of our hierarchy classes/ids/tags
            css_blocks = []
            
            # Very basic regex parsing to pull out blocks
            # Look for all selectors and their blocks: 'selector { property: value; }'
            for match in re.finditer(r'([^{]+)\s*\{([^}]+)\}', content):
                selectors_text = match.group(1).strip()
                rules = match.group(2).strip()
                
                # Check if this selector matches anything in our hierarchy
                is_relevant = False
                for sel in selectors_text.split(','):
                    sel = sel.strip()
                    if not sel: continue
                    
                    # Direct ID match
                    for id_ in ids_to_check:
                        if f"#{id_}" in sel:
                            is_relevant = True
                    
                    # Direct Class match
                    for cls in classes_to_check:
                        if f".{cls}" in sel:
                            is_relevant = True
                            
                    # Direct Tag match
                    for tag in tags_to_check:
                        # Ensure it's not a substring of a class name (e.g. body tag vs .some-body-class)
                        if re.search(r'(^|\s)' + re.escape(tag) + r'($|\s|:|\.|#)', sel):
                            is_relevant = True
                            
                if is_relevant:
                    # Look for dangerous properties
                    warnings = []
                    if 'overflow: hidden' in rules or 'overflow-y: hidden' in rules or 'overflow-x: hidden' in rules:
                        warnings.append("⚠️ ATTENTION: `overflow: hidden` found here! This might chop off children!")
                    if 'display: none' in rules:
                        warnings.append("⚠️ ATTENTION: `display: none` found here! This hides the element completely!")
                    if re.search(r'\bheight:\s*(?!auto)[^;]+', rules) or re.search(r'\bmax-height:\s*(?!none)[^;]+', rules):
                        warnings.append("⚠️ ATTENTION: Strict height bounds found! Check if they are clipping large children!")
                    if 'z-index' in rules:
                        warnings.append("ℹ️ Has z-index property.")
                        
                    formatted_block = f"{selectors_text} {{\n  {rules}\n}}"
                    if warnings:
                        formatted_block = "\n".join(warnings) + "\n" + formatted_block
                        
                    css_blocks.append(formatted_block)
            
            # Format report
            report = [
                f"## Layout Diagnostics for `{selector}`\n",
                "### DOM Hierarchy (Target up to <body>):",
                "This shows the chain of containers that wrap your element."
            ]
            
            for i, level in enumerate(hierarchy):
                prefix = "  " * i + "↳ " if i > 0 else "🎯 "
                report.append(f"{prefix}{level}")
                
            report.append("\n### Relevant CSS Layout Rules:")
            report.append("These are the CSS rules applying to the target element and all its parent containers.")
            report.append("Look for `height`, `overflow`, `z-index`, `position`, and `display` values that might hide it.")
            report.append("-----")
            
            if css_blocks:
                report.append("\n\n".join(css_blocks))
            else:
                report.append("*No internal CSS rules found matching the hierarchy classes.*")
                
            return success_result(
                "\n".join(report),
                duration_ms=(time.time() - start_time) * 1000
            )
            
        except Exception as e:
            log.error(f"Failed to check layout: {e}")
            return error_result(f"Failed to check layout: {str(e)}")
